version: '3.8'

services:
  cybernews:
    build: .
    container_name: cyber_news_aggregator
    restart: unless-stopped
    volumes:
      - ./output:/app/output
    environment:
      - TZ=Europe/Istanbul
    networks:
      - cybernews_network

networks:
  cybernews_network:
    driver: bridge
